services:
  link-center:
    image: link-center:latest
    ports:
      - "${UI_PORT:-3000}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHON_TTS_URL=${PYTHON_TTS_URL:-http://host.docker.internal:14000}
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:15
    container_name: link-center-postgres
    environment:
      POSTGRES_USER: filecenter
      POSTGRES_PASSWORD: Fc2026PgLc!
      POSTGRES_DB: filecenter
    volumes:
      - link-center-postgres-vol:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  link-center-postgres-vol:
